package com.github.se.polyfit.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF64558F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8DDFF)
val onPrimaryContainerLight = Color(0xFF201047)
val secondaryLight = Color(0xFF65558F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DDFF)
val onSecondaryContainerLight = Color(0xFF210F47)
val tertiaryLight = Color(0xFF8B4A61)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E3)
val onTertiaryContainerLight = Color(0xFF3A071E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE6E0EC)
val onSurfaceVariantLight = Color(0xFF49454E)

val outlineLight = Color(0xFF7158E2)
val outlineVariantLight = Color(0xFFCD84F1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFCEBDFE)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFDF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F2FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFECE6EE)
val surfaceContainerHighestLight = Color(0xFFE6E1E9)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val DarkOutiline = Color(0xFFFF7538)
val DarkOutilineVariant = Color(0xFFFF4F00)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val PrimaryPurple = Color(0xFF7158E2)
val PrimaryPink = Color(0xFFCD84F1)
val SecondaryGrey = Color(0xFF8f8f8f)
val GradientButtonPink = Color(0xFF4A00E0)
val GradientButtonPurple = Color(0xFF8E2DE2)
val GradientButtonGrey = Color(0xFFE0E0E0)
val DeleteIconRed = Color(0xFFFF7575)
val BorderPurple = Color(0xFFD8D1F5)
val GhostPurpe = Color(0xFFEDE9FF)
